services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sif-dev-admin:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - CORE_API_URL=http://host.docker.internal:3333
      - MINIO_UPLOAD_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: npm run dev
